import * as Types from "../../../bindings/ben/desktop/api/types/models";
import * as DesktopCoreModels from "../../../bindings/ben/desktop/internal/desktopcore/models";
import * as ThemeModels from "../../../bindings/ben/desktop/internal/palette/models";
import * as PlaybackModels from "../../../bindings/ben/desktop/internal/playback/models";

export { DesktopCoreModels, PlaybackModels, Types };

export type ActivityStatus = Types.ActivityStatus;
export type AlbumListItem = Types.AlbumListItem;
export type AlbumTrackItem = Types.AlbumTrackItem;
export type AlbumVariantItem = Types.AlbumVariantItem;
export type ArtworkRef = Types.ArtworkRef;
export type ArtistListItem = Types.ArtistListItem;
export type CacheEntryItem = Types.CacheEntryItem;
export type CacheOverview = Types.CacheOverview;
export type InspectSummary = Types.InspectSummary;
export type InviteCodeResult = Types.InviteCodeResult;
export type InviteJoinRequestRecord = Types.InviteJoinRequestRecord;
export type IssuedInviteRecord = Types.IssuedInviteRecord;
export type JoinSession = Types.JoinSession;
export type JobPhase = DesktopCoreModels.JobPhase;
export type JobSnapshot = DesktopCoreModels.JobSnapshot;
export type LibraryCheckpointStatus = Types.LibraryCheckpointStatus;
export type LibraryMemberStatus = Types.LibraryMemberStatus;
export type LibraryOplogDiagnostics = Types.LibraryOplogDiagnostics;
export type LibrarySummary = Types.LibrarySummary;
export type LikedRecordingItem = Types.LikedRecordingItem;
export type LocalContext = Types.LocalContext;
export type PageInfo = Types.PageInfo;
export type PlaybackPreparationStatus = Types.PlaybackPreparationStatus;
export type PlaylistListItem = Types.PlaylistListItem;
export type PlaylistTrackItem = Types.PlaylistTrackItem;
export type RecordingListItem = Types.RecordingListItem;
export type SessionEntry = PlaybackModels.SessionEntry;
export type SessionItem = PlaybackModels.SessionItem;
export type SessionSnapshot = PlaybackModels.SessionSnapshot;
export type ThemePalette = ThemeModels.ThemePalette;
export type ThemePaletteColor = ThemeModels.PaletteColor;
export type ThemePaletteTone = ThemeModels.PaletteTone;

export const DEFAULT_PAGE_SIZE = 60;
export const TRACK_PAGE_SIZE = 120;
