// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as apitypes$0 from "../../../../../ben/desktop/api/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as desktopcore$0 from "../../../../../ben/desktop/internal/desktopcore/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as playback$0 from "../../../../../ben/desktop/internal/playback/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "catalog:changed": apitypes$0.CatalogChangeEvent;
            "jobs:snapshot": desktopcore$0.JobSnapshot;
            "notifications:snapshot": apitypes$0.NotificationSnapshot;
            "pin:changed": apitypes$0.PinChangeEvent;
            "playback:queue": playback$0.QueueEventSnapshot;
            "playback:transport": playback$0.TransportEventSnapshot;
            "theme:preferences": apitypes$0.ThemePreferences;
        }
    }
}
