//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playback$0 from "../../../../../ben/desktop/internal/playback/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "playback:snapshot": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = playback$0.SessionSnapshot.createFrom;

configure();
