// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export enum JobPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    JobPhaseQueued = "queued",
    JobPhaseRunning = "running",
    JobPhaseCompleted = "completed",
    JobPhaseFailed = "failed",
};

export class JobSnapshot {
    "jobId": string;
    "kind": string;
    "libraryId"?: string;
    "phase": JobPhase;
    "progress"?: number;
    "message"?: string;
    "error"?: string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "finishedAt"?: time$0.Time;

    /** Creates a new JobSnapshot instance. */
    constructor($$source: Partial<JobSnapshot> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = JobPhase.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): JobSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobSnapshot($$parsedSource as Partial<JobSnapshot>);
    }
}
