// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AccentRoles {
    "default": Color;
    "hover": Color;
    "pressed": Color;
    "subtle": Color;
    "onAccent": Color;

    /** Creates a new AccentRoles instance. */
    constructor($$source: Partial<AccentRoles> = {}) {
        if (!("default" in $$source)) {
            this["default"] = (new Color());
        }
        if (!("hover" in $$source)) {
            this["hover"] = (new Color());
        }
        if (!("pressed" in $$source)) {
            this["pressed"] = (new Color());
        }
        if (!("subtle" in $$source)) {
            this["subtle"] = (new Color());
        }
        if (!("onAccent" in $$source)) {
            this["onAccent"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccentRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): AccentRoles {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField0_0($$parsedSource["default"]);
        }
        if ("hover" in $$parsedSource) {
            $$parsedSource["hover"] = $$createField1_0($$parsedSource["hover"]);
        }
        if ("pressed" in $$parsedSource) {
            $$parsedSource["pressed"] = $$createField2_0($$parsedSource["pressed"]);
        }
        if ("subtle" in $$parsedSource) {
            $$parsedSource["subtle"] = $$createField3_0($$parsedSource["subtle"]);
        }
        if ("onAccent" in $$parsedSource) {
            $$parsedSource["onAccent"] = $$createField4_0($$parsedSource["onAccent"]);
        }
        return new AccentRoles($$parsedSource as Partial<AccentRoles>);
    }
}

export class ArtworkCandidate {
    "color": Color;
    "share": number;
    "centrality": number;

    /** Creates a new ArtworkCandidate instance. */
    constructor($$source: Partial<ArtworkCandidate> = {}) {
        if (!("color" in $$source)) {
            this["color"] = (new Color());
        }
        if (!("share" in $$source)) {
            this["share"] = 0;
        }
        if (!("centrality" in $$source)) {
            this["centrality"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtworkCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtworkCandidate {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField0_0($$parsedSource["color"]);
        }
        return new ArtworkCandidate($$parsedSource as Partial<ArtworkCandidate>);
    }
}

export enum ArtworkClass {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ArtworkClassNeutral = "neutral",
    ArtworkClassSingleHue = "single-hue",
    ArtworkClassMulticolor = "multicolor",
};

export class ArtworkIdentity {
    "class": ArtworkClass;
    "atmosphere": Color;
    "accent"?: Color | null;
    "candidates": ArtworkCandidate[];

    /** Creates a new ArtworkIdentity instance. */
    constructor($$source: Partial<ArtworkIdentity> = {}) {
        if (!("class" in $$source)) {
            this["class"] = ArtworkClass.$zero;
        }
        if (!("atmosphere" in $$source)) {
            this["atmosphere"] = (new Color());
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArtworkIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): ArtworkIdentity {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("atmosphere" in $$parsedSource) {
            $$parsedSource["atmosphere"] = $$createField1_0($$parsedSource["atmosphere"]);
        }
        if ("accent" in $$parsedSource) {
            $$parsedSource["accent"] = $$createField2_0($$parsedSource["accent"]);
        }
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField3_0($$parsedSource["candidates"]);
        }
        return new ArtworkIdentity($$parsedSource as Partial<ArtworkIdentity>);
    }
}

export class BorderRoles {
    "subtle": Color;
    "default": Color;
    "strong": Color;
    "focus": Color;

    /** Creates a new BorderRoles instance. */
    constructor($$source: Partial<BorderRoles> = {}) {
        if (!("subtle" in $$source)) {
            this["subtle"] = (new Color());
        }
        if (!("default" in $$source)) {
            this["default"] = (new Color());
        }
        if (!("strong" in $$source)) {
            this["strong"] = (new Color());
        }
        if (!("focus" in $$source)) {
            this["focus"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BorderRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): BorderRoles {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subtle" in $$parsedSource) {
            $$parsedSource["subtle"] = $$createField0_0($$parsedSource["subtle"]);
        }
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField1_0($$parsedSource["default"]);
        }
        if ("strong" in $$parsedSource) {
            $$parsedSource["strong"] = $$createField2_0($$parsedSource["strong"]);
        }
        if ("focus" in $$parsedSource) {
            $$parsedSource["focus"] = $$createField3_0($$parsedSource["focus"]);
        }
        return new BorderRoles($$parsedSource as Partial<BorderRoles>);
    }
}

export class Color {
    "hex": string;
    "r": number;
    "g": number;
    "b": number;
    "population"?: number;
    "lightness": number;
    "chroma": number;
    "hue": number;

    /** Creates a new Color instance. */
    constructor($$source: Partial<Color> = {}) {
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("r" in $$source)) {
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            this["b"] = 0;
        }
        if (!("lightness" in $$source)) {
            this["lightness"] = 0;
        }
        if (!("chroma" in $$source)) {
            this["chroma"] = 0;
        }
        if (!("hue" in $$source)) {
            this["hue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Color instance from a string or object.
     */
    static createFrom($$source: any = {}): Color {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Color($$parsedSource as Partial<Color>);
    }
}

/**
 * CompatibilityPalette is a temporary bridge for the pre-token UI. New UI
 * must not consume it.
 */
export class CompatibilityPalette {
    "themeScale": PaletteTone[];
    "accentScale": PaletteTone[];

    /** Creates a new CompatibilityPalette instance. */
    constructor($$source: Partial<CompatibilityPalette> = {}) {
        if (!("themeScale" in $$source)) {
            this["themeScale"] = [];
        }
        if (!("accentScale" in $$source)) {
            this["accentScale"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompatibilityPalette instance from a string or object.
     */
    static createFrom($$source: any = {}): CompatibilityPalette {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("themeScale" in $$parsedSource) {
            $$parsedSource["themeScale"] = $$createField0_0($$parsedSource["themeScale"]);
        }
        if ("accentScale" in $$parsedSource) {
            $$parsedSource["accentScale"] = $$createField1_0($$parsedSource["accentScale"]);
        }
        return new CompatibilityPalette($$parsedSource as Partial<CompatibilityPalette>);
    }
}

export class ContentRoles {
    "primary": Color;
    "secondary": Color;
    "disabled": Color;
    "inverse": Color;

    /** Creates a new ContentRoles instance. */
    constructor($$source: Partial<ContentRoles> = {}) {
        if (!("primary" in $$source)) {
            this["primary"] = (new Color());
        }
        if (!("secondary" in $$source)) {
            this["secondary"] = (new Color());
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = (new Color());
        }
        if (!("inverse" in $$source)) {
            this["inverse"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): ContentRoles {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary" in $$parsedSource) {
            $$parsedSource["primary"] = $$createField0_0($$parsedSource["primary"]);
        }
        if ("secondary" in $$parsedSource) {
            $$parsedSource["secondary"] = $$createField1_0($$parsedSource["secondary"]);
        }
        if ("disabled" in $$parsedSource) {
            $$parsedSource["disabled"] = $$createField2_0($$parsedSource["disabled"]);
        }
        if ("inverse" in $$parsedSource) {
            $$parsedSource["inverse"] = $$createField3_0($$parsedSource["inverse"]);
        }
        return new ContentRoles($$parsedSource as Partial<ContentRoles>);
    }
}

export class PaletteTone {
    "tone": number;
    "color": Color;

    /** Creates a new PaletteTone instance. */
    constructor($$source: Partial<PaletteTone> = {}) {
        if (!("tone" in $$source)) {
            this["tone"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaletteTone instance from a string or object.
     */
    static createFrom($$source: any = {}): PaletteTone {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField1_0($$parsedSource["color"]);
        }
        return new PaletteTone($$parsedSource as Partial<PaletteTone>);
    }
}

export class Scheme {
    "surface": SurfaceRoles;
    "content": ContentRoles;
    "border": BorderRoles;
    "accent": AccentRoles;
    "status": StatusRoles;

    /** Creates a new Scheme instance. */
    constructor($$source: Partial<Scheme> = {}) {
        if (!("surface" in $$source)) {
            this["surface"] = (new SurfaceRoles());
        }
        if (!("content" in $$source)) {
            this["content"] = (new ContentRoles());
        }
        if (!("border" in $$source)) {
            this["border"] = (new BorderRoles());
        }
        if (!("accent" in $$source)) {
            this["accent"] = (new AccentRoles());
        }
        if (!("status" in $$source)) {
            this["status"] = (new StatusRoles());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Scheme instance from a string or object.
     */
    static createFrom($$source: any = {}): Scheme {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("surface" in $$parsedSource) {
            $$parsedSource["surface"] = $$createField0_0($$parsedSource["surface"]);
        }
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        if ("border" in $$parsedSource) {
            $$parsedSource["border"] = $$createField2_0($$parsedSource["border"]);
        }
        if ("accent" in $$parsedSource) {
            $$parsedSource["accent"] = $$createField3_0($$parsedSource["accent"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField4_0($$parsedSource["status"]);
        }
        return new Scheme($$parsedSource as Partial<Scheme>);
    }
}

export class StatusRole {
    "default": Color;
    "subtle": Color;
    "on": Color;

    /** Creates a new StatusRole instance. */
    constructor($$source: Partial<StatusRole> = {}) {
        if (!("default" in $$source)) {
            this["default"] = (new Color());
        }
        if (!("subtle" in $$source)) {
            this["subtle"] = (new Color());
        }
        if (!("on" in $$source)) {
            this["on"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusRole instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusRole {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField0_0($$parsedSource["default"]);
        }
        if ("subtle" in $$parsedSource) {
            $$parsedSource["subtle"] = $$createField1_0($$parsedSource["subtle"]);
        }
        if ("on" in $$parsedSource) {
            $$parsedSource["on"] = $$createField2_0($$parsedSource["on"]);
        }
        return new StatusRole($$parsedSource as Partial<StatusRole>);
    }
}

export class StatusRoles {
    "danger": StatusRole;
    "warning": StatusRole;
    "success": StatusRole;

    /** Creates a new StatusRoles instance. */
    constructor($$source: Partial<StatusRoles> = {}) {
        if (!("danger" in $$source)) {
            this["danger"] = (new StatusRole());
        }
        if (!("warning" in $$source)) {
            this["warning"] = (new StatusRole());
        }
        if (!("success" in $$source)) {
            this["success"] = (new StatusRole());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusRoles {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("danger" in $$parsedSource) {
            $$parsedSource["danger"] = $$createField0_0($$parsedSource["danger"]);
        }
        if ("warning" in $$parsedSource) {
            $$parsedSource["warning"] = $$createField1_0($$parsedSource["warning"]);
        }
        if ("success" in $$parsedSource) {
            $$parsedSource["success"] = $$createField2_0($$parsedSource["success"]);
        }
        return new StatusRoles($$parsedSource as Partial<StatusRoles>);
    }
}

export class SurfaceRoles {
    "canvas": Color;
    "recessed": Color;
    "default": Color;
    "raised": Color;
    "overlay": Color;

    /** Creates a new SurfaceRoles instance. */
    constructor($$source: Partial<SurfaceRoles> = {}) {
        if (!("canvas" in $$source)) {
            this["canvas"] = (new Color());
        }
        if (!("recessed" in $$source)) {
            this["recessed"] = (new Color());
        }
        if (!("default" in $$source)) {
            this["default"] = (new Color());
        }
        if (!("raised" in $$source)) {
            this["raised"] = (new Color());
        }
        if (!("overlay" in $$source)) {
            this["overlay"] = (new Color());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SurfaceRoles instance from a string or object.
     */
    static createFrom($$source: any = {}): SurfaceRoles {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("canvas" in $$parsedSource) {
            $$parsedSource["canvas"] = $$createField0_0($$parsedSource["canvas"]);
        }
        if ("recessed" in $$parsedSource) {
            $$parsedSource["recessed"] = $$createField1_0($$parsedSource["recessed"]);
        }
        if ("default" in $$parsedSource) {
            $$parsedSource["default"] = $$createField2_0($$parsedSource["default"]);
        }
        if ("raised" in $$parsedSource) {
            $$parsedSource["raised"] = $$createField3_0($$parsedSource["raised"]);
        }
        if ("overlay" in $$parsedSource) {
            $$parsedSource["overlay"] = $$createField4_0($$parsedSource["overlay"]);
        }
        return new SurfaceRoles($$parsedSource as Partial<SurfaceRoles>);
    }
}

/**
 * Theme is the versioned, component-facing result of artwork analysis.
 * Foundations are intentionally kept private; callers consume semantic roles.
 */
export class Theme {
    "version": number;
    "artwork": ArtworkIdentity;
    "light": Scheme;
    "dark": Scheme;
    "compatibility": CompatibilityPalette;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("artwork" in $$source)) {
            this["artwork"] = (new ArtworkIdentity());
        }
        if (!("light" in $$source)) {
            this["light"] = (new Scheme());
        }
        if (!("dark" in $$source)) {
            this["dark"] = (new Scheme());
        }
        if (!("compatibility" in $$source)) {
            this["compatibility"] = (new CompatibilityPalette());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType13;
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artwork" in $$parsedSource) {
            $$parsedSource["artwork"] = $$createField1_0($$parsedSource["artwork"]);
        }
        if ("light" in $$parsedSource) {
            $$parsedSource["light"] = $$createField2_0($$parsedSource["light"]);
        }
        if ("dark" in $$parsedSource) {
            $$parsedSource["dark"] = $$createField3_0($$parsedSource["dark"]);
        }
        if ("compatibility" in $$parsedSource) {
            $$parsedSource["compatibility"] = $$createField4_0($$parsedSource["compatibility"]);
        }
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

// Private type creation functions
const $$createType0 = Color.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ArtworkCandidate.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PaletteTone.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SurfaceRoles.createFrom;
const $$createType7 = ContentRoles.createFrom;
const $$createType8 = BorderRoles.createFrom;
const $$createType9 = AccentRoles.createFrom;
const $$createType10 = StatusRoles.createFrom;
const $$createType11 = StatusRole.createFrom;
const $$createType12 = ArtworkIdentity.createFrom;
const $$createType13 = Scheme.createFrom;
const $$createType14 = CompatibilityPalette.createFrom;
