// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PaletteColor {
    "hex": string;
    "r": number;
    "g": number;
    "b": number;
    "population": number;
    "lightness": number;
    "chroma": number;
    "hue": number;

    /** Creates a new PaletteColor instance. */
    constructor($$source: Partial<PaletteColor> = {}) {
        if (!("hex" in $$source)) {
            this["hex"] = "";
        }
        if (!("r" in $$source)) {
            this["r"] = 0;
        }
        if (!("g" in $$source)) {
            this["g"] = 0;
        }
        if (!("b" in $$source)) {
            this["b"] = 0;
        }
        if (!("population" in $$source)) {
            this["population"] = 0;
        }
        if (!("lightness" in $$source)) {
            this["lightness"] = 0;
        }
        if (!("chroma" in $$source)) {
            this["chroma"] = 0;
        }
        if (!("hue" in $$source)) {
            this["hue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaletteColor instance from a string or object.
     */
    static createFrom($$source: any = {}): PaletteColor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaletteColor($$parsedSource as Partial<PaletteColor>);
    }
}

export class PaletteTone {
    "tone": number;
    "color": PaletteColor;

    /** Creates a new PaletteTone instance. */
    constructor($$source: Partial<PaletteTone> = {}) {
        if (!("tone" in $$source)) {
            this["tone"] = 0;
        }
        if (!("color" in $$source)) {
            this["color"] = (new PaletteColor());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaletteTone instance from a string or object.
     */
    static createFrom($$source: any = {}): PaletteTone {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("color" in $$parsedSource) {
            $$parsedSource["color"] = $$createField1_0($$parsedSource["color"]);
        }
        return new PaletteTone($$parsedSource as Partial<PaletteTone>);
    }
}

export class ThemePalette {
    "primary"?: PaletteColor | null;
    "dark"?: PaletteColor | null;
    "light"?: PaletteColor | null;
    "accent"?: PaletteColor | null;
    "themeScale": PaletteTone[];
    "accentScale": PaletteTone[];

    /** Creates a new ThemePalette instance. */
    constructor($$source: Partial<ThemePalette> = {}) {
        if (!("themeScale" in $$source)) {
            this["themeScale"] = [];
        }
        if (!("accentScale" in $$source)) {
            this["accentScale"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemePalette instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemePalette {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("primary" in $$parsedSource) {
            $$parsedSource["primary"] = $$createField0_0($$parsedSource["primary"]);
        }
        if ("dark" in $$parsedSource) {
            $$parsedSource["dark"] = $$createField1_0($$parsedSource["dark"]);
        }
        if ("light" in $$parsedSource) {
            $$parsedSource["light"] = $$createField2_0($$parsedSource["light"]);
        }
        if ("accent" in $$parsedSource) {
            $$parsedSource["accent"] = $$createField3_0($$parsedSource["accent"]);
        }
        if ("themeScale" in $$parsedSource) {
            $$parsedSource["themeScale"] = $$createField4_0($$parsedSource["themeScale"]);
        }
        if ("accentScale" in $$parsedSource) {
            $$parsedSource["accentScale"] = $$createField5_0($$parsedSource["accentScale"]);
        }
        return new ThemePalette($$parsedSource as Partial<ThemePalette>);
    }
}

// Private type creation functions
const $$createType0 = PaletteColor.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = PaletteTone.createFrom;
const $$createType3 = $Create.Array($$createType2);
