/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracksRouteRouteImport } from './routes/tracks/route'
import { Route as SharingRouteRouteImport } from './routes/sharing/route'
import { Route as PlaylistsRouteRouteImport } from './routes/playlists/route'
import { Route as OperationsRouteRouteImport } from './routes/operations/route'
import { Route as LibrariesRouteRouteImport } from './routes/libraries/route'
import { Route as CacheRouteRouteImport } from './routes/cache/route'
import { Route as ArtistsRouteRouteImport } from './routes/artists/route'
import { Route as AlbumsRouteRouteImport } from './routes/albums/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsLikedRouteRouteImport } from './routes/playlists_/liked/route'
import { Route as PlaylistsPlaylistIdRouteRouteImport } from './routes/playlists_/$playlistId/route'
import { Route as ArtistsArtistIdRouteRouteImport } from './routes/artists_/$artistId/route'
import { Route as AlbumsAlbumIdRouteRouteImport } from './routes/albums_/$albumId/route'

const TracksRouteRoute = TracksRouteRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const SharingRouteRoute = SharingRouteRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRouteRoute = PlaylistsRouteRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRouteRoute = OperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesRouteRoute = LibrariesRouteRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const CacheRouteRoute = CacheRouteRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRouteRoute = ArtistsRouteRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRouteRoute = AlbumsRouteRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsLikedRouteRoute = PlaylistsLikedRouteRouteImport.update({
  id: '/playlists_/liked',
  path: '/playlists/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRouteRoute =
  PlaylistsPlaylistIdRouteRouteImport.update({
    id: '/playlists_/$playlistId',
    path: '/playlists/$playlistId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArtistsArtistIdRouteRoute = ArtistsArtistIdRouteRouteImport.update({
  id: '/artists_/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRouteRoute = AlbumsAlbumIdRouteRouteImport.update({
  id: '/albums_/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteRoute
  '/artists': typeof ArtistsRouteRoute
  '/cache': typeof CacheRouteRoute
  '/libraries': typeof LibrariesRouteRoute
  '/operations': typeof OperationsRouteRoute
  '/playlists': typeof PlaylistsRouteRoute
  '/sharing': typeof SharingRouteRoute
  '/tracks': typeof TracksRouteRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof ArtistsArtistIdRouteRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRouteRoute
  '/playlists/liked': typeof PlaylistsLikedRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteRoute
  '/artists': typeof ArtistsRouteRoute
  '/cache': typeof CacheRouteRoute
  '/libraries': typeof LibrariesRouteRoute
  '/operations': typeof OperationsRouteRoute
  '/playlists': typeof PlaylistsRouteRoute
  '/sharing': typeof SharingRouteRoute
  '/tracks': typeof TracksRouteRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRouteRoute
  '/artists/$artistId': typeof ArtistsArtistIdRouteRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRouteRoute
  '/playlists/liked': typeof PlaylistsLikedRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteRoute
  '/artists': typeof ArtistsRouteRoute
  '/cache': typeof CacheRouteRoute
  '/libraries': typeof LibrariesRouteRoute
  '/operations': typeof OperationsRouteRoute
  '/playlists': typeof PlaylistsRouteRoute
  '/sharing': typeof SharingRouteRoute
  '/tracks': typeof TracksRouteRoute
  '/albums_/$albumId': typeof AlbumsAlbumIdRouteRoute
  '/artists_/$artistId': typeof ArtistsArtistIdRouteRoute
  '/playlists_/$playlistId': typeof PlaylistsPlaylistIdRouteRoute
  '/playlists_/liked': typeof PlaylistsLikedRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums'
    | '/artists'
    | '/cache'
    | '/libraries'
    | '/operations'
    | '/playlists'
    | '/sharing'
    | '/tracks'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/playlists/liked'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/artists'
    | '/cache'
    | '/libraries'
    | '/operations'
    | '/playlists'
    | '/sharing'
    | '/tracks'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/playlists/liked'
  id:
    | '__root__'
    | '/'
    | '/albums'
    | '/artists'
    | '/cache'
    | '/libraries'
    | '/operations'
    | '/playlists'
    | '/sharing'
    | '/tracks'
    | '/albums_/$albumId'
    | '/artists_/$artistId'
    | '/playlists_/$playlistId'
    | '/playlists_/liked'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsRouteRoute: typeof AlbumsRouteRoute
  ArtistsRouteRoute: typeof ArtistsRouteRoute
  CacheRouteRoute: typeof CacheRouteRoute
  LibrariesRouteRoute: typeof LibrariesRouteRoute
  OperationsRouteRoute: typeof OperationsRouteRoute
  PlaylistsRouteRoute: typeof PlaylistsRouteRoute
  SharingRouteRoute: typeof SharingRouteRoute
  TracksRouteRoute: typeof TracksRouteRoute
  AlbumsAlbumIdRouteRoute: typeof AlbumsAlbumIdRouteRoute
  ArtistsArtistIdRouteRoute: typeof ArtistsArtistIdRouteRoute
  PlaylistsPlaylistIdRouteRoute: typeof PlaylistsPlaylistIdRouteRoute
  PlaylistsLikedRouteRoute: typeof PlaylistsLikedRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries': {
      id: '/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LibrariesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cache': {
      id: '/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof CacheRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists_/liked': {
      id: '/playlists_/liked'
      path: '/playlists/liked'
      fullPath: '/playlists/liked'
      preLoaderRoute: typeof PlaylistsLikedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists_/$playlistId': {
      id: '/playlists_/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists_/$artistId': {
      id: '/artists_/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums_/$albumId': {
      id: '/albums_/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsRouteRoute: AlbumsRouteRoute,
  ArtistsRouteRoute: ArtistsRouteRoute,
  CacheRouteRoute: CacheRouteRoute,
  LibrariesRouteRoute: LibrariesRouteRoute,
  OperationsRouteRoute: OperationsRouteRoute,
  PlaylistsRouteRoute: PlaylistsRouteRoute,
  SharingRouteRoute: SharingRouteRoute,
  TracksRouteRoute: TracksRouteRoute,
  AlbumsAlbumIdRouteRoute: AlbumsAlbumIdRouteRoute,
  ArtistsArtistIdRouteRoute: ArtistsArtistIdRouteRoute,
  PlaylistsPlaylistIdRouteRoute: PlaylistsPlaylistIdRouteRoute,
  PlaylistsLikedRouteRoute: PlaylistsLikedRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
