// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "../../api/types/models.js";

export enum ContextKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextKindAlbum = "album",
    ContextKindPlaylist = "playlist",
    ContextKindLiked = "liked",
    ContextKindTracks = "tracks",
    ContextKindRecording = "recording",
    ContextKindCustom = "custom",
};

export class ContextQueue {
    "kind": ContextKind;
    "id": string;
    "title"?: string;
    "entries": ContextWindowEntry[];
    "startIndex": number;
    "currentIndex": number;
    "resumeIndex": number;
    "shuffleBag"?: number[];
    "hasBefore"?: boolean;
    "hasAfter"?: boolean;
    "windowStart"?: number;
    "windowCount"?: number;
    "totalCount"?: number;
    "live"?: boolean;
    "loading"?: boolean;
    "sourceVersion"?: number;
    "shuffleSeed"?: number;
    "source"?: PlaybackSourceDescriptor | null;
    "anchor"?: PlaybackSourceAnchor | null;

    /** Creates a new ContextQueue instance. */
    constructor($$source: Partial<ContextQueue> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = ContextKind.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("startIndex" in $$source)) {
            this["startIndex"] = 0;
        }
        if (!("currentIndex" in $$source)) {
            this["currentIndex"] = 0;
        }
        if (!("resumeIndex" in $$source)) {
            this["resumeIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextQueue instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextQueue {
        const $$createField3_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField17_0 = $$createType4;
        const $$createField18_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        if ("shuffleBag" in $$parsedSource) {
            $$parsedSource["shuffleBag"] = $$createField7_0($$parsedSource["shuffleBag"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField17_0($$parsedSource["source"]);
        }
        if ("anchor" in $$parsedSource) {
            $$parsedSource["anchor"] = $$createField18_0($$parsedSource["anchor"]);
        }
        return new ContextQueue($$parsedSource as Partial<ContextQueue>);
    }
}

export class ContextQueueEventSnapshot {
    "title"?: string;
    "entries": QueueEntryEventSnapshot[];
    "hasBefore"?: boolean;
    "hasAfter"?: boolean;
    "totalCount"?: number;
    "currentIndex"?: number;
    "resumeIndex"?: number;
    "windowStart"?: number;
    "windowCount"?: number;
    "loading"?: boolean;
    "sourceVersion"?: number;
    "source"?: PlaybackSourceDescriptor | null;
    "anchor"?: PlaybackSourceAnchor | null;
    "shuffleBag"?: number[];

    /** Creates a new ContextQueueEventSnapshot instance. */
    constructor($$source: Partial<ContextQueueEventSnapshot> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextQueueEventSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextQueueEventSnapshot {
        const $$createField1_0 = $$createType8;
        const $$createField11_0 = $$createType4;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField11_0($$parsedSource["source"]);
        }
        if ("anchor" in $$parsedSource) {
            $$parsedSource["anchor"] = $$createField12_0($$parsedSource["anchor"]);
        }
        if ("shuffleBag" in $$parsedSource) {
            $$parsedSource["shuffleBag"] = $$createField13_0($$parsedSource["shuffleBag"]);
        }
        return new ContextQueueEventSnapshot($$parsedSource as Partial<ContextQueueEventSnapshot>);
    }
}

export enum ContextRebasePolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextRebaseFrozen = "frozen",
    ContextRebaseLive = "live",
};

export enum CurrentLane {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CurrentLaneContext = "context",
    CurrentLaneUser = "user",
};

export enum EntryOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EntryOriginContext = "context",
    EntryOriginQueued = "queued",
};

export class EntryPreparation {
    "entryId": string;
    "status": apitypes$0.PlaybackPreparationStatus;

    /** Creates a new EntryPreparation instance. */
    constructor($$source: Partial<EntryPreparation> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new apitypes$0.PlaybackPreparationStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryPreparation instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryPreparation {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new EntryPreparation($$parsedSource as Partial<EntryPreparation>);
    }
}

export class PlaybackSkipEvent {
    "eventId": string;
    "message": string;
    "count": number;
    "stopped": boolean;
    "firstEntry"?: SessionEntry | null;
    "occurredAt": string;

    /** Creates a new PlaybackSkipEvent instance. */
    constructor($$source: Partial<PlaybackSkipEvent> = {}) {
        if (!("eventId" in $$source)) {
            this["eventId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("stopped" in $$source)) {
            this["stopped"] = false;
        }
        if (!("occurredAt" in $$source)) {
            this["occurredAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackSkipEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackSkipEvent {
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("firstEntry" in $$parsedSource) {
            $$parsedSource["firstEntry"] = $$createField4_0($$parsedSource["firstEntry"]);
        }
        return new PlaybackSkipEvent($$parsedSource as Partial<PlaybackSkipEvent>);
    }
}

export class PlaybackSourceAnchor {
    "entryKey"?: string;
    "recordingId"?: string;
    "sourceItemId"?: string;

    /** Creates a new PlaybackSourceAnchor instance. */
    constructor($$source: Partial<PlaybackSourceAnchor> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackSourceAnchor instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackSourceAnchor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackSourceAnchor($$parsedSource as Partial<PlaybackSourceAnchor>);
    }
}

export class PlaybackSourceDescriptor {
    "kind": ContextKind;
    "id": string;
    "title"?: string;
    "rebasePolicy"?: ContextRebasePolicy;
    "live"?: boolean;

    /** Creates a new PlaybackSourceDescriptor instance. */
    constructor($$source: Partial<PlaybackSourceDescriptor> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = ContextKind.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackSourceDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackSourceDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackSourceDescriptor($$parsedSource as Partial<PlaybackSourceDescriptor>);
    }
}

export class PlaybackTargetRef {
    "logicalRecordingId"?: string;
    "exactVariantRecordingId"?: string;
    "resolutionPolicy"?: PlaybackTargetResolution;

    /** Creates a new PlaybackTargetRef instance. */
    constructor($$source: Partial<PlaybackTargetRef> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackTargetRef instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackTargetRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackTargetRef($$parsedSource as Partial<PlaybackTargetRef>);
    }
}

export enum PlaybackTargetResolution {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlaybackTargetResolutionPreferred = "preferred",
    PlaybackTargetResolutionExact = "exact",
};

export class QueueEntryEventSnapshot {
    "entryId": string;
    "origin"?: EntryOrigin;
    "contextIndex"?: number;
    "item": SessionItemEvent;

    /** Creates a new QueueEntryEventSnapshot instance. */
    constructor($$source: Partial<QueueEntryEventSnapshot> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("item" in $$source)) {
            this["item"] = (new SessionItemEvent());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueEntryEventSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueEntryEventSnapshot {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField3_0($$parsedSource["item"]);
        }
        return new QueueEntryEventSnapshot($$parsedSource as Partial<QueueEntryEventSnapshot>);
    }
}

export class QueueEventSnapshot {
    "contextQueue": ContextQueueEventSnapshot | null;
    "userQueue": QueueEntryEventSnapshot[];
    "entryAvailability": { [_ in string]?: apitypes$0.RecordingPlaybackAvailability };
    "queueLength": number;
    "queueVersion"?: number;

    /** Creates a new QueueEventSnapshot instance. */
    constructor($$source: Partial<QueueEventSnapshot> = {}) {
        if (!("contextQueue" in $$source)) {
            this["contextQueue"] = null;
        }
        if (!("userQueue" in $$source)) {
            this["userQueue"] = [];
        }
        if (!("entryAvailability" in $$source)) {
            this["entryAvailability"] = {};
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueEventSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueEventSnapshot {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextQueue" in $$parsedSource) {
            $$parsedSource["contextQueue"] = $$createField0_0($$parsedSource["contextQueue"]);
        }
        if ("userQueue" in $$parsedSource) {
            $$parsedSource["userQueue"] = $$createField1_0($$parsedSource["userQueue"]);
        }
        if ("entryAvailability" in $$parsedSource) {
            $$parsedSource["entryAvailability"] = $$createField2_0($$parsedSource["entryAvailability"]);
        }
        return new QueueEventSnapshot($$parsedSource as Partial<QueueEventSnapshot>);
    }
}

export class QueuePlan {
    "entry"?: SessionEntry | null;
    "lane"?: CurrentLane;
    "planned": boolean;

    /** Creates a new QueuePlan instance. */
    constructor($$source: Partial<QueuePlan> = {}) {
        if (!("planned" in $$source)) {
            this["planned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueuePlan instance from a string or object.
     */
    static createFrom($$source: any = {}): QueuePlan {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField0_0($$parsedSource["entry"]);
        }
        return new QueuePlan($$parsedSource as Partial<QueuePlan>);
    }
}

export enum RepeatMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RepeatOff = "off",
    RepeatAll = "all",
    RepeatOne = "one",
};

export enum ResolutionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ResolutionModeLibrary = "library",
    ResolutionModeExplicit = "explicit",
};

export class SessionEntry {
    "entryId": string;
    "origin": EntryOrigin;
    "contextIndex"?: number;
    "item": SessionItem;

    /** Creates a new SessionEntry instance. */
    constructor($$source: Partial<SessionEntry> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = EntryOrigin.$zero;
        }
        if (!("item" in $$source)) {
            this["item"] = (new SessionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEntry {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField3_0($$parsedSource["item"]);
        }
        return new SessionEntry($$parsedSource as Partial<SessionEntry>);
    }
}

export const ContextWindowEntry = SessionEntry;
export type ContextWindowEntry = SessionEntry;

export class SessionItem {
    "libraryRecordingId"?: string;
    "variantRecordingId"?: string;
    "recordingId": string;
    "title": string;
    "subtitle": string;
    "durationMs": number;
    "artworkRef": string;
    "sourceKind": string;
    "sourceId": string;
    "sourceItemId": string;
    "albumId"?: string;
    "variantAlbumId"?: string;
    "resolutionMode"?: ResolutionMode;
    "target"?: PlaybackTargetRef;

    /** Creates a new SessionItem instance. */
    constructor($$source: Partial<SessionItem> = {}) {
        if (!("recordingId" in $$source)) {
            this["recordingId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("artworkRef" in $$source)) {
            this["artworkRef"] = "";
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("sourceItemId" in $$source)) {
            this["sourceItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItem {
        const $$createField13_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField13_0($$parsedSource["target"]);
        }
        return new SessionItem($$parsedSource as Partial<SessionItem>);
    }
}

export class SessionItemEvent {
    "libraryRecordingId"?: string;
    "variantRecordingId"?: string;
    "recordingId": string;
    "title": string;
    "subtitle": string;
    "durationMs": number;
    "artworkRef": string;
    "sourceKind"?: string;
    "sourceId"?: string;
    "sourceItemId"?: string;
    "albumId"?: string;
    "variantAlbumId"?: string;

    /** Creates a new SessionItemEvent instance. */
    constructor($$source: Partial<SessionItemEvent> = {}) {
        if (!("recordingId" in $$source)) {
            this["recordingId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("artworkRef" in $$source)) {
            this["artworkRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItemEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItemEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionItemEvent($$parsedSource as Partial<SessionItemEvent>);
    }
}

export class SessionSnapshot {
    "contextQueue"?: ContextQueue | null;
    "userQueue": SessionEntry[];
    "currentEntryId"?: string;
    "currentEntry"?: SessionEntry | null;
    "currentItem"?: SessionItem | null;
    "loadingEntry"?: SessionEntry | null;
    "loadingItem"?: SessionItem | null;
    "upcomingEntries": SessionEntry[];
    "currentLane"?: CurrentLane;
    "nextPlanned"?: QueuePlan | null;
    "preloadedPlan"?: QueuePlan | null;
    "repeatMode": RepeatMode;
    "shuffle": boolean;
    "volume": number;
    "status": Status;
    "positionMs": number;
    "positionCapturedAtMs"?: number;
    "durationMs"?: number | null;
    "updatedAt": string;
    "lastError"?: string;
    "currentSourceKind"?: apitypes$0.PlaybackSourceKind;
    "currentPreparation"?: EntryPreparation | null;
    "loadingPreparation"?: EntryPreparation | null;
    "nextPreparation"?: EntryPreparation | null;
    "entryAvailability"?: { [_ in string]?: apitypes$0.RecordingPlaybackAvailability };
    "lastSkipEvent"?: PlaybackSkipEvent | null;
    "queueLength": number;
    "nextEntrySeq"?: number;
    "queueVersion"?: number;

    /** Creates a new SessionSnapshot instance. */
    constructor($$source: Partial<SessionSnapshot> = {}) {
        if (!("userQueue" in $$source)) {
            this["userQueue"] = [];
        }
        if (!("upcomingEntries" in $$source)) {
            this["upcomingEntries"] = [];
        }
        if (!("repeatMode" in $$source)) {
            this["repeatMode"] = RepeatMode.$zero;
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSnapshot {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType10;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType20;
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $$createType22;
        const $$createField10_0 = $$createType22;
        const $$createField21_0 = $$createType24;
        const $$createField22_0 = $$createType24;
        const $$createField23_0 = $$createType24;
        const $$createField24_0 = $$createType15;
        const $$createField25_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextQueue" in $$parsedSource) {
            $$parsedSource["contextQueue"] = $$createField0_0($$parsedSource["contextQueue"]);
        }
        if ("userQueue" in $$parsedSource) {
            $$parsedSource["userQueue"] = $$createField1_0($$parsedSource["userQueue"]);
        }
        if ("currentEntry" in $$parsedSource) {
            $$parsedSource["currentEntry"] = $$createField3_0($$parsedSource["currentEntry"]);
        }
        if ("currentItem" in $$parsedSource) {
            $$parsedSource["currentItem"] = $$createField4_0($$parsedSource["currentItem"]);
        }
        if ("loadingEntry" in $$parsedSource) {
            $$parsedSource["loadingEntry"] = $$createField5_0($$parsedSource["loadingEntry"]);
        }
        if ("loadingItem" in $$parsedSource) {
            $$parsedSource["loadingItem"] = $$createField6_0($$parsedSource["loadingItem"]);
        }
        if ("upcomingEntries" in $$parsedSource) {
            $$parsedSource["upcomingEntries"] = $$createField7_0($$parsedSource["upcomingEntries"]);
        }
        if ("nextPlanned" in $$parsedSource) {
            $$parsedSource["nextPlanned"] = $$createField9_0($$parsedSource["nextPlanned"]);
        }
        if ("preloadedPlan" in $$parsedSource) {
            $$parsedSource["preloadedPlan"] = $$createField10_0($$parsedSource["preloadedPlan"]);
        }
        if ("currentPreparation" in $$parsedSource) {
            $$parsedSource["currentPreparation"] = $$createField21_0($$parsedSource["currentPreparation"]);
        }
        if ("loadingPreparation" in $$parsedSource) {
            $$parsedSource["loadingPreparation"] = $$createField22_0($$parsedSource["loadingPreparation"]);
        }
        if ("nextPreparation" in $$parsedSource) {
            $$parsedSource["nextPreparation"] = $$createField23_0($$parsedSource["nextPreparation"]);
        }
        if ("entryAvailability" in $$parsedSource) {
            $$parsedSource["entryAvailability"] = $$createField24_0($$parsedSource["entryAvailability"]);
        }
        if ("lastSkipEvent" in $$parsedSource) {
            $$parsedSource["lastSkipEvent"] = $$createField25_0($$parsedSource["lastSkipEvent"]);
        }
        return new SessionSnapshot($$parsedSource as Partial<SessionSnapshot>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusPaused = "paused",
    StatusPlaying = "playing",
    StatusPending = "pending",
};

export class TransportEventSnapshot {
    "currentEntry": QueueEntryEventSnapshot | null;
    "loadingEntry": QueueEntryEventSnapshot | null;
    "loadingPreparation": EntryPreparation | null;
    "repeatMode": RepeatMode;
    "shuffle": boolean;
    "volume": number;
    "status": Status;
    "positionMs": number;
    "positionCapturedAtMs"?: number;
    "durationMs": number | null;
    "lastError": string;

    /** Creates a new TransportEventSnapshot instance. */
    constructor($$source: Partial<TransportEventSnapshot> = {}) {
        if (!("currentEntry" in $$source)) {
            this["currentEntry"] = null;
        }
        if (!("loadingEntry" in $$source)) {
            this["loadingEntry"] = null;
        }
        if (!("loadingPreparation" in $$source)) {
            this["loadingPreparation"] = null;
        }
        if (!("repeatMode" in $$source)) {
            this["repeatMode"] = RepeatMode.$zero;
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = null;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransportEventSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): TransportEventSnapshot {
        const $$createField0_0 = $$createType27;
        const $$createField1_0 = $$createType27;
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentEntry" in $$parsedSource) {
            $$parsedSource["currentEntry"] = $$createField0_0($$parsedSource["currentEntry"]);
        }
        if ("loadingEntry" in $$parsedSource) {
            $$parsedSource["loadingEntry"] = $$createField1_0($$parsedSource["loadingEntry"]);
        }
        if ("loadingPreparation" in $$parsedSource) {
            $$parsedSource["loadingPreparation"] = $$createField2_0($$parsedSource["loadingPreparation"]);
        }
        return new TransportEventSnapshot($$parsedSource as Partial<TransportEventSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = SessionEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = PlaybackSourceDescriptor.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = PlaybackSourceAnchor.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = QueueEntryEventSnapshot.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = apitypes$0.PlaybackPreparationStatus.createFrom;
const $$createType10 = $Create.Nullable($$createType0);
const $$createType11 = SessionItemEvent.createFrom;
const $$createType12 = ContextQueueEventSnapshot.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = apitypes$0.RecordingPlaybackAvailability.createFrom;
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = SessionItem.createFrom;
const $$createType17 = PlaybackTargetRef.createFrom;
const $$createType18 = ContextQueue.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Nullable($$createType16);
const $$createType21 = QueuePlan.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = EntryPreparation.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = PlaybackSkipEvent.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $Create.Nullable($$createType7);
