// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "../../api/types/models.js";

export enum ContextKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextKindAlbum = "album",
    ContextKindPlaylist = "playlist",
    ContextKindLiked = "liked",
    ContextKindRecording = "recording",
    ContextKindCustom = "custom",
};

export class ContextQueue {
    "kind": ContextKind;
    "id": string;
    "title"?: string;
    "entries": SessionEntry[];
    "startIndex": number;
    "currentIndex": number;
    "resumeIndex": number;
    "shuffleBag"?: number[];

    /** Creates a new ContextQueue instance. */
    constructor($$source: Partial<ContextQueue> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = ContextKind.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("startIndex" in $$source)) {
            this["startIndex"] = 0;
        }
        if (!("currentIndex" in $$source)) {
            this["currentIndex"] = 0;
        }
        if (!("resumeIndex" in $$source)) {
            this["resumeIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextQueue instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextQueue {
        const $$createField3_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        if ("shuffleBag" in $$parsedSource) {
            $$parsedSource["shuffleBag"] = $$createField7_0($$parsedSource["shuffleBag"]);
        }
        return new ContextQueue($$parsedSource as Partial<ContextQueue>);
    }
}

export enum CurrentLane {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CurrentLaneContext = "context",
    CurrentLaneUser = "user",
};

export enum EntryOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EntryOriginContext = "context",
    EntryOriginQueued = "queued",
};

export class EntryPreparation {
    "entryId": string;
    "status": apitypes$0.PlaybackPreparationStatus;

    /** Creates a new EntryPreparation instance. */
    constructor($$source: Partial<EntryPreparation> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new apitypes$0.PlaybackPreparationStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryPreparation instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryPreparation {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new EntryPreparation($$parsedSource as Partial<EntryPreparation>);
    }
}

export class PlaybackContextInput {
    "Kind": ContextKind;
    "ID": string;
    "Title": string;
    "Items": SessionItem[];
    "StartIndex": number;

    /** Creates a new PlaybackContextInput instance. */
    constructor($$source: Partial<PlaybackContextInput> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = ContextKind.$zero;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }
        if (!("StartIndex" in $$source)) {
            this["StartIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackContextInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackContextInput {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField3_0($$parsedSource["Items"]);
        }
        return new PlaybackContextInput($$parsedSource as Partial<PlaybackContextInput>);
    }
}

export class PlaybackSkipEvent {
    "eventId": string;
    "message": string;
    "count": number;
    "stopped": boolean;
    "firstEntry"?: SessionEntry | null;
    "occurredAt": string;

    /** Creates a new PlaybackSkipEvent instance. */
    constructor($$source: Partial<PlaybackSkipEvent> = {}) {
        if (!("eventId" in $$source)) {
            this["eventId"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("stopped" in $$source)) {
            this["stopped"] = false;
        }
        if (!("occurredAt" in $$source)) {
            this["occurredAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackSkipEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackSkipEvent {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("firstEntry" in $$parsedSource) {
            $$parsedSource["firstEntry"] = $$createField4_0($$parsedSource["firstEntry"]);
        }
        return new PlaybackSkipEvent($$parsedSource as Partial<PlaybackSkipEvent>);
    }
}

export class PlaybackTargetRef {
    "logicalRecordingId"?: string;
    "exactVariantRecordingId"?: string;
    "resolutionPolicy"?: PlaybackTargetResolution;

    /** Creates a new PlaybackTargetRef instance. */
    constructor($$source: Partial<PlaybackTargetRef> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackTargetRef instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackTargetRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaybackTargetRef($$parsedSource as Partial<PlaybackTargetRef>);
    }
}

export enum PlaybackTargetResolution {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlaybackTargetResolutionPreferred = "preferred",
    PlaybackTargetResolutionExact = "exact",
};

export class QueuePlan {
    "entry"?: SessionEntry | null;
    "lane"?: CurrentLane;
    "planned": boolean;

    /** Creates a new QueuePlan instance. */
    constructor($$source: Partial<QueuePlan> = {}) {
        if (!("planned" in $$source)) {
            this["planned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueuePlan instance from a string or object.
     */
    static createFrom($$source: any = {}): QueuePlan {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField0_0($$parsedSource["entry"]);
        }
        return new QueuePlan($$parsedSource as Partial<QueuePlan>);
    }
}

export enum RepeatMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RepeatOff = "off",
    RepeatAll = "all",
    RepeatOne = "one",
};

export enum ResolutionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ResolutionModeLibrary = "library",
    ResolutionModeExplicit = "explicit",
};

export class SessionEntry {
    "entryId": string;
    "origin": EntryOrigin;
    "contextIndex"?: number;
    "item": SessionItem;

    /** Creates a new SessionEntry instance. */
    constructor($$source: Partial<SessionEntry> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = EntryOrigin.$zero;
        }
        if (!("item" in $$source)) {
            this["item"] = (new SessionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEntry {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField3_0($$parsedSource["item"]);
        }
        return new SessionEntry($$parsedSource as Partial<SessionEntry>);
    }
}

export class SessionItem {
    "libraryRecordingId"?: string;
    "variantRecordingId"?: string;
    "recordingId": string;
    "title": string;
    "subtitle": string;
    "durationMs": number;
    "artworkRef": string;
    "sourceKind": string;
    "sourceId": string;
    "sourceItemId": string;
    "albumId"?: string;
    "variantAlbumId"?: string;
    "resolutionMode"?: ResolutionMode;
    "target"?: PlaybackTargetRef;

    /** Creates a new SessionItem instance. */
    constructor($$source: Partial<SessionItem> = {}) {
        if (!("recordingId" in $$source)) {
            this["recordingId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("artworkRef" in $$source)) {
            this["artworkRef"] = "";
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("sourceItemId" in $$source)) {
            this["sourceItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItem {
        const $$createField13_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField13_0($$parsedSource["target"]);
        }
        return new SessionItem($$parsedSource as Partial<SessionItem>);
    }
}

export class SessionSnapshot {
    "contextQueue"?: ContextQueue | null;
    "userQueue": SessionEntry[];
    "currentEntryId"?: string;
    "currentEntry"?: SessionEntry | null;
    "currentItem"?: SessionItem | null;
    "loadingEntry"?: SessionEntry | null;
    "loadingItem"?: SessionItem | null;
    "upcomingEntries": SessionEntry[];
    "currentLane"?: CurrentLane;
    "nextPlanned"?: QueuePlan | null;
    "preloadedPlan"?: QueuePlan | null;
    "repeatMode": RepeatMode;
    "shuffle": boolean;
    "volume": number;
    "status": Status;
    "positionMs": number;
    "durationMs"?: number | null;
    "updatedAt": string;
    "lastError"?: string;
    "currentSourceKind"?: apitypes$0.PlaybackSourceKind;
    "currentPreparation"?: EntryPreparation | null;
    "loadingPreparation"?: EntryPreparation | null;
    "nextPreparation"?: EntryPreparation | null;
    "entryAvailability"?: { [_ in string]?: apitypes$0.RecordingPlaybackAvailability };
    "lastSkipEvent"?: PlaybackSkipEvent | null;
    "queueLength": number;
    "nextEntrySeq"?: number;

    /** Creates a new SessionSnapshot instance. */
    constructor($$source: Partial<SessionSnapshot> = {}) {
        if (!("userQueue" in $$source)) {
            this["userQueue"] = [];
        }
        if (!("upcomingEntries" in $$source)) {
            this["upcomingEntries"] = [];
        }
        if (!("repeatMode" in $$source)) {
            this["repeatMode"] = RepeatMode.$zero;
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSnapshot {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType10;
        const $$createField7_0 = $$createType1;
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType12;
        const $$createField20_0 = $$createType14;
        const $$createField21_0 = $$createType14;
        const $$createField22_0 = $$createType14;
        const $$createField23_0 = $$createType16;
        const $$createField24_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextQueue" in $$parsedSource) {
            $$parsedSource["contextQueue"] = $$createField0_0($$parsedSource["contextQueue"]);
        }
        if ("userQueue" in $$parsedSource) {
            $$parsedSource["userQueue"] = $$createField1_0($$parsedSource["userQueue"]);
        }
        if ("currentEntry" in $$parsedSource) {
            $$parsedSource["currentEntry"] = $$createField3_0($$parsedSource["currentEntry"]);
        }
        if ("currentItem" in $$parsedSource) {
            $$parsedSource["currentItem"] = $$createField4_0($$parsedSource["currentItem"]);
        }
        if ("loadingEntry" in $$parsedSource) {
            $$parsedSource["loadingEntry"] = $$createField5_0($$parsedSource["loadingEntry"]);
        }
        if ("loadingItem" in $$parsedSource) {
            $$parsedSource["loadingItem"] = $$createField6_0($$parsedSource["loadingItem"]);
        }
        if ("upcomingEntries" in $$parsedSource) {
            $$parsedSource["upcomingEntries"] = $$createField7_0($$parsedSource["upcomingEntries"]);
        }
        if ("nextPlanned" in $$parsedSource) {
            $$parsedSource["nextPlanned"] = $$createField9_0($$parsedSource["nextPlanned"]);
        }
        if ("preloadedPlan" in $$parsedSource) {
            $$parsedSource["preloadedPlan"] = $$createField10_0($$parsedSource["preloadedPlan"]);
        }
        if ("currentPreparation" in $$parsedSource) {
            $$parsedSource["currentPreparation"] = $$createField20_0($$parsedSource["currentPreparation"]);
        }
        if ("loadingPreparation" in $$parsedSource) {
            $$parsedSource["loadingPreparation"] = $$createField21_0($$parsedSource["loadingPreparation"]);
        }
        if ("nextPreparation" in $$parsedSource) {
            $$parsedSource["nextPreparation"] = $$createField22_0($$parsedSource["nextPreparation"]);
        }
        if ("entryAvailability" in $$parsedSource) {
            $$parsedSource["entryAvailability"] = $$createField23_0($$parsedSource["entryAvailability"]);
        }
        if ("lastSkipEvent" in $$parsedSource) {
            $$parsedSource["lastSkipEvent"] = $$createField24_0($$parsedSource["lastSkipEvent"]);
        }
        return new SessionSnapshot($$parsedSource as Partial<SessionSnapshot>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusPaused = "paused",
    StatusPlaying = "playing",
    StatusPending = "pending",
};

// Private type creation functions
const $$createType0 = SessionEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = apitypes$0.PlaybackPreparationStatus.createFrom;
const $$createType4 = SessionItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Nullable($$createType0);
const $$createType7 = PlaybackTargetRef.createFrom;
const $$createType8 = ContextQueue.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Nullable($$createType4);
const $$createType11 = QueuePlan.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = EntryPreparation.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = apitypes$0.RecordingPlaybackAvailability.createFrom;
const $$createType16 = $Create.Map($Create.Any, $$createType15);
const $$createType17 = PlaybackSkipEvent.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
