// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "../../api/types/models.js";

export enum ContextKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ContextKindAlbum = "album",
    ContextKindPlaylist = "playlist",
    ContextKindLiked = "liked",
    ContextKindRecording = "recording",
    ContextKindCustom = "custom",
};

export enum EntryOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EntryOriginContext = "context",
    EntryOriginQueued = "queued",
};

export class EntryPreparation {
    "entryId": string;
    "status": apitypes$0.PlaybackPreparationStatus;

    /** Creates a new EntryPreparation instance. */
    constructor($$source: Partial<EntryPreparation> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = (new apitypes$0.PlaybackPreparationStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryPreparation instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryPreparation {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField1_0($$parsedSource["status"]);
        }
        return new EntryPreparation($$parsedSource as Partial<EntryPreparation>);
    }
}

export class HistoryEntry {
    "entry": SessionEntry;
    "playedAt": string;

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("entry" in $$source)) {
            this["entry"] = (new SessionEntry());
        }
        if (!("playedAt" in $$source)) {
            this["playedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField0_0($$parsedSource["entry"]);
        }
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export class PlaybackContext {
    "kind": ContextKind;
    "id": string;
    "title"?: string;
    "entries": SessionEntry[];

    /** Creates a new PlaybackContext instance. */
    constructor($$source: Partial<PlaybackContext> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = ContextKind.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackContext instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackContext {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new PlaybackContext($$parsedSource as Partial<PlaybackContext>);
    }
}

export class PlaybackContextInput {
    "Kind": ContextKind;
    "ID": string;
    "Title": string;
    "Items": SessionItem[];
    "StartIndex": number;

    /** Creates a new PlaybackContextInput instance. */
    constructor($$source: Partial<PlaybackContextInput> = {}) {
        if (!("Kind" in $$source)) {
            this["Kind"] = ContextKind.$zero;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Items" in $$source)) {
            this["Items"] = [];
        }
        if (!("StartIndex" in $$source)) {
            this["StartIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaybackContextInput instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaybackContextInput {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Items" in $$parsedSource) {
            $$parsedSource["Items"] = $$createField3_0($$parsedSource["Items"]);
        }
        return new PlaybackContextInput($$parsedSource as Partial<PlaybackContextInput>);
    }
}

export enum RepeatMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RepeatOff = "off",
    RepeatAll = "all",
    RepeatOne = "one",
};

export class SessionEntry {
    "entryId": string;
    "origin": EntryOrigin;
    "contextIndex"?: number;
    "item": SessionItem;

    /** Creates a new SessionEntry instance. */
    constructor($$source: Partial<SessionEntry> = {}) {
        if (!("entryId" in $$source)) {
            this["entryId"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = EntryOrigin.$zero;
        }
        if (!("item" in $$source)) {
            this["item"] = (new SessionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionEntry {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField3_0($$parsedSource["item"]);
        }
        return new SessionEntry($$parsedSource as Partial<SessionEntry>);
    }
}

export class SessionItem {
    "recordingId": string;
    "title": string;
    "subtitle": string;
    "durationMs": number;
    "artworkRef": string;
    "sourceKind": string;
    "sourceId": string;
    "sourceItemId": string;
    "albumId"?: string;

    /** Creates a new SessionItem instance. */
    constructor($$source: Partial<SessionItem> = {}) {
        if (!("recordingId" in $$source)) {
            this["recordingId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("artworkRef" in $$source)) {
            this["artworkRef"] = "";
        }
        if (!("sourceKind" in $$source)) {
            this["sourceKind"] = "";
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = "";
        }
        if (!("sourceItemId" in $$source)) {
            this["sourceItemId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionItem($$parsedSource as Partial<SessionItem>);
    }
}

export class SessionSnapshot {
    "context"?: PlaybackContext | null;
    "queuedEntries": SessionEntry[];
    "history": HistoryEntry[];
    "currentEntryId"?: string;
    "currentEntry"?: SessionEntry | null;
    "currentItem"?: SessionItem | null;
    "loadingEntry"?: SessionEntry | null;
    "loadingItem"?: SessionItem | null;
    "upcomingEntries": SessionEntry[];
    "currentOrigin"?: EntryOrigin;
    "currentContextIndex": number;
    "resumeContextIndex": number;
    "shuffleCycle"?: number[];
    "repeatMode": RepeatMode;
    "shuffle": boolean;
    "volume": number;
    "status": Status;
    "positionMs": number;
    "durationMs"?: number | null;
    "updatedAt": string;
    "lastError"?: string;
    "currentSourceKind"?: apitypes$0.PlaybackSourceKind;
    "currentPreparation"?: EntryPreparation | null;
    "loadingPreparation"?: EntryPreparation | null;
    "nextPreparation"?: EntryPreparation | null;
    "queueLength": number;
    "nextEntrySeq"?: number;

    /** Creates a new SessionSnapshot instance. */
    constructor($$source: Partial<SessionSnapshot> = {}) {
        if (!("queuedEntries" in $$source)) {
            this["queuedEntries"] = [];
        }
        if (!("history" in $$source)) {
            this["history"] = [];
        }
        if (!("upcomingEntries" in $$source)) {
            this["upcomingEntries"] = [];
        }
        if (!("currentContextIndex" in $$source)) {
            this["currentContextIndex"] = 0;
        }
        if (!("resumeContextIndex" in $$source)) {
            this["resumeContextIndex"] = 0;
        }
        if (!("repeatMode" in $$source)) {
            this["repeatMode"] = RepeatMode.$zero;
        }
        if (!("shuffle" in $$source)) {
            this["shuffle"] = false;
        }
        if (!("volume" in $$source)) {
            this["volume"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("positionMs" in $$source)) {
            this["positionMs"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = "";
        }
        if (!("queueLength" in $$source)) {
            this["queueLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSnapshot {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType8;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType9;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType2;
        const $$createField12_0 = $$createType11;
        const $$createField22_0 = $$createType13;
        const $$createField23_0 = $$createType13;
        const $$createField24_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField0_0($$parsedSource["context"]);
        }
        if ("queuedEntries" in $$parsedSource) {
            $$parsedSource["queuedEntries"] = $$createField1_0($$parsedSource["queuedEntries"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField2_0($$parsedSource["history"]);
        }
        if ("currentEntry" in $$parsedSource) {
            $$parsedSource["currentEntry"] = $$createField4_0($$parsedSource["currentEntry"]);
        }
        if ("currentItem" in $$parsedSource) {
            $$parsedSource["currentItem"] = $$createField5_0($$parsedSource["currentItem"]);
        }
        if ("loadingEntry" in $$parsedSource) {
            $$parsedSource["loadingEntry"] = $$createField6_0($$parsedSource["loadingEntry"]);
        }
        if ("loadingItem" in $$parsedSource) {
            $$parsedSource["loadingItem"] = $$createField7_0($$parsedSource["loadingItem"]);
        }
        if ("upcomingEntries" in $$parsedSource) {
            $$parsedSource["upcomingEntries"] = $$createField8_0($$parsedSource["upcomingEntries"]);
        }
        if ("shuffleCycle" in $$parsedSource) {
            $$parsedSource["shuffleCycle"] = $$createField12_0($$parsedSource["shuffleCycle"]);
        }
        if ("currentPreparation" in $$parsedSource) {
            $$parsedSource["currentPreparation"] = $$createField22_0($$parsedSource["currentPreparation"]);
        }
        if ("loadingPreparation" in $$parsedSource) {
            $$parsedSource["loadingPreparation"] = $$createField23_0($$parsedSource["loadingPreparation"]);
        }
        if ("nextPreparation" in $$parsedSource) {
            $$parsedSource["nextPreparation"] = $$createField24_0($$parsedSource["nextPreparation"]);
        }
        return new SessionSnapshot($$parsedSource as Partial<SessionSnapshot>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusPaused = "paused",
    StatusPlaying = "playing",
    StatusPending = "pending",
};

// Private type creation functions
const $$createType0 = apitypes$0.PlaybackPreparationStatus.createFrom;
const $$createType1 = SessionEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = SessionItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = PlaybackContext.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = HistoryEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Nullable($$createType1);
const $$createType10 = $Create.Nullable($$createType3);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = EntryPreparation.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
