// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function CheckForUpdates(): $CancellablePromise<apitypes$0.AppUpdateCheckResult> {
    return $Call.ByID(2657121147).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStatus(): $CancellablePromise<apitypes$0.AppUpdateStatus> {
    return $Call.ByID(302389770).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = apitypes$0.AppUpdateCheckResult.createFrom;
const $$createType1 = apitypes$0.AppUpdateStatus.createFrom;
