// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function CleanupCache(req: apitypes$0.CacheCleanupRequest): $CancellablePromise<apitypes$0.CacheCleanupResult> {
    return $Call.ByID(2385592778, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCacheOverview(): $CancellablePromise<apitypes$0.CacheOverview> {
    return $Call.ByID(1845485441).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListCacheEntries(req: apitypes$0.CacheEntryListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.CacheEntryItem>> {
    return $Call.ByID(1594342766, req).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = apitypes$0.CacheCleanupResult.createFrom;
const $$createType1 = apitypes$0.CacheOverview.createFrom;
const $$createType2 = apitypes$0.CacheEntryItem.createFrom;
const $$createType3 = apitypes$0.Page.createFrom($$createType2);
