// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function AddPlaylistItem(req: apitypes$0.PlaylistAddItemRequest): $CancellablePromise<apitypes$0.PlaylistItemRecord> {
    return $Call.ByID(1149566815, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreatePlaylist(name: string, kind: string): $CancellablePromise<apitypes$0.PlaylistRecord> {
    return $Call.ByID(3136748453, name, kind).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeletePlaylist(playlistID: string): $CancellablePromise<void> {
    return $Call.ByID(603886286, playlistID);
}

export function GetAlbum(albumID: string): $CancellablePromise<apitypes$0.AlbumListItem> {
    return $Call.ByID(4169437780, albumID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetArtist(artistID: string): $CancellablePromise<apitypes$0.ArtistListItem> {
    return $Call.ByID(835509606, artistID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPlaylistSummary(playlistID: string): $CancellablePromise<apitypes$0.PlaylistListItem> {
    return $Call.ByID(238686077, playlistID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetRecording(recordingID: string): $CancellablePromise<apitypes$0.RecordingListItem> {
    return $Call.ByID(3202044900, recordingID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function IsRecordingLiked(recordingID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3993001207, recordingID);
}

export function LikeRecording(recordingID: string): $CancellablePromise<void> {
    return $Call.ByID(373110587, recordingID);
}

export function ListAlbumTracks(req: apitypes$0.AlbumTrackListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumTrackItem>> {
    return $Call.ByID(814108678, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListAlbumVariants(req: apitypes$0.AlbumVariantListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumVariantItem>> {
    return $Call.ByID(3257450384, req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListAlbums(req: apitypes$0.AlbumListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumListItem>> {
    return $Call.ByID(1639265315, req).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListArtistAlbums(req: apitypes$0.ArtistAlbumListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumListItem>> {
    return $Call.ByID(1401976912, req).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListArtists(req: apitypes$0.ArtistListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.ArtistListItem>> {
    return $Call.ByID(4143009445, req).then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListLikedRecordings(req: apitypes$0.LikedRecordingListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.LikedRecordingItem>> {
    return $Call.ByID(3968279140, req).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListPlaylistTracks(req: apitypes$0.PlaylistTrackListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.PlaylistTrackItem>> {
    return $Call.ByID(2707610533, req).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListPlaylists(req: apitypes$0.PlaylistListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.PlaylistListItem>> {
    return $Call.ByID(1310037898, req).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListRecordingVariants(req: apitypes$0.RecordingVariantListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.RecordingVariantItem>> {
    return $Call.ByID(3908440204, req).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ListRecordings(req: apitypes$0.RecordingListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.RecordingListItem>> {
    return $Call.ByID(4010206991, req).then(($result: any) => {
        return $$createType19($result);
    });
}

export function MovePlaylistItem(req: apitypes$0.PlaylistMoveItemRequest): $CancellablePromise<apitypes$0.PlaylistItemRecord> {
    return $Call.ByID(2979409731, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemovePlaylistItem(playlistID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(2115202114, playlistID, itemID);
}

export function RenamePlaylist(playlistID: string, name: string): $CancellablePromise<apitypes$0.PlaylistRecord> {
    return $Call.ByID(1642517447, playlistID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SetPreferredAlbumVariant(albumID: string, variantAlbumID: string): $CancellablePromise<void> {
    return $Call.ByID(247746186, albumID, variantAlbumID);
}

export function SetPreferredRecordingVariant(recordingID: string, variantRecordingID: string): $CancellablePromise<void> {
    return $Call.ByID(218982714, recordingID, variantRecordingID);
}

export function UnlikeRecording(recordingID: string): $CancellablePromise<void> {
    return $Call.ByID(4179180402, recordingID);
}

// Private type creation functions
const $$createType0 = apitypes$0.PlaylistItemRecord.createFrom;
const $$createType1 = apitypes$0.PlaylistRecord.createFrom;
const $$createType2 = apitypes$0.AlbumListItem.createFrom;
const $$createType3 = apitypes$0.ArtistListItem.createFrom;
const $$createType4 = apitypes$0.PlaylistListItem.createFrom;
const $$createType5 = apitypes$0.RecordingListItem.createFrom;
const $$createType6 = apitypes$0.AlbumTrackItem.createFrom;
const $$createType7 = apitypes$0.Page.createFrom($$createType6);
const $$createType8 = apitypes$0.AlbumVariantItem.createFrom;
const $$createType9 = apitypes$0.Page.createFrom($$createType8);
const $$createType10 = apitypes$0.Page.createFrom($$createType2);
const $$createType11 = apitypes$0.Page.createFrom($$createType3);
const $$createType12 = apitypes$0.LikedRecordingItem.createFrom;
const $$createType13 = apitypes$0.Page.createFrom($$createType12);
const $$createType14 = apitypes$0.PlaylistTrackItem.createFrom;
const $$createType15 = apitypes$0.Page.createFrom($$createType14);
const $$createType16 = apitypes$0.Page.createFrom($$createType4);
const $$createType17 = apitypes$0.RecordingVariantItem.createFrom;
const $$createType18 = apitypes$0.Page.createFrom($$createType17);
const $$createType19 = apitypes$0.Page.createFrom($$createType5);
