// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopcore$0 from "./internal/desktopcore/models.js";

export function ApproveJoinRequest(requestID: string, role: string): $CancellablePromise<void> {
    return $Call.ByID(2154804979, requestID, role);
}

export function CancelJoinSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(567196285, sessionID);
}

export function CreateInviteCode(req: apitypes$0.InviteCodeRequest): $CancellablePromise<apitypes$0.InviteCodeResult> {
    return $Call.ByID(954474485, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetJoinSession(sessionID: string): $CancellablePromise<apitypes$0.JoinSession> {
    return $Call.ByID(3812262537, sessionID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListIssuedInvites(status: string): $CancellablePromise<apitypes$0.IssuedInviteRecord[]> {
    return $Call.ByID(2625364054, status).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListJoinRequests(status: string): $CancellablePromise<apitypes$0.InviteJoinRequestRecord[]> {
    return $Call.ByID(2833420939, status).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RejectJoinRequest(requestID: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(1240171767, requestID, reason);
}

export function RevokeIssuedInvite(inviteID: string, reason: string): $CancellablePromise<void> {
    return $Call.ByID(413876291, inviteID, reason);
}

export function StartFinalizeJoinSession(sessionID: string): $CancellablePromise<desktopcore$0.JobSnapshot> {
    return $Call.ByID(2247074811, sessionID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StartJoinFromInvite(req: apitypes$0.JoinFromInviteInput): $CancellablePromise<apitypes$0.JoinSession> {
    return $Call.ByID(759325766, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = apitypes$0.InviteCodeResult.createFrom;
const $$createType1 = apitypes$0.JoinSession.createFrom;
const $$createType2 = apitypes$0.IssuedInviteRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = apitypes$0.InviteJoinRequestRecord.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = desktopcore$0.JobSnapshot.createFrom;
