// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function ApproveJoinRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(2154804979, requestID);
}

export function CancelJoinAttempt(attemptID: string): $CancellablePromise<void> {
    return $Call.ByID(619997408, attemptID);
}

export function CreateInvite(req: apitypes$0.InviteCreateRequest): $CancellablePromise<apitypes$0.InviteRecord> {
    return $Call.ByID(89410432, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteInvite(inviteID: string): $CancellablePromise<void> {
    return $Call.ByID(1402632995, inviteID);
}

export function GetJoinAttempt(attemptID: string): $CancellablePromise<apitypes$0.JoinAttempt> {
    return $Call.ByID(2092108876, attemptID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListActiveInvites(): $CancellablePromise<apitypes$0.InviteRecord[]> {
    return $Call.ByID(2559279215).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListJoinRequests(): $CancellablePromise<apitypes$0.InviteJoinRequestRecord[]> {
    return $Call.ByID(2833420939).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RejectJoinRequest(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1240171767, requestID);
}

export function StartJoinFromInvite(req: apitypes$0.JoinFromInviteInput): $CancellablePromise<apitypes$0.JoinAttempt> {
    return $Call.ByID(759325766, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = apitypes$0.InviteRecord.createFrom;
const $$createType1 = apitypes$0.JoinAttempt.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = apitypes$0.InviteJoinRequestRecord.createFrom;
const $$createType4 = $Create.Array($$createType3);
