// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopcore$0 from "./internal/desktopcore/models.js";

export function GetJob(jobID: string): $CancellablePromise<[desktopcore$0.JobSnapshot, boolean]> {
    return $Call.ByID(2388243421, jobID).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

export function ListJobs(libraryID: string): $CancellablePromise<desktopcore$0.JobSnapshot[]> {
    return $Call.ByID(2535795914, libraryID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SubscribeJobEvents(): $CancellablePromise<string> {
    return $Call.ByID(4271791156);
}

// Private type creation functions
const $$createType0 = desktopcore$0.JobSnapshot.createFrom;
const $$createType1 = $Create.Array($$createType0);
