// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopcore$0 from "./internal/desktopcore/models.js";

export function ActiveLibrary(): $CancellablePromise<[apitypes$0.LibrarySummary, boolean]> {
    return $Call.ByID(3730238604).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

export function AddScanRoots(roots: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1310922240, roots).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateLibrary(name: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(510473898, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteLibrary(libraryID: string): $CancellablePromise<void> {
    return $Call.ByID(533926343, libraryID);
}

export function LeaveLibrary(libraryID: string): $CancellablePromise<void> {
    return $Call.ByID(3061401293, libraryID);
}

export function ListLibraries(): $CancellablePromise<apitypes$0.LibrarySummary[]> {
    return $Call.ByID(2014903258).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListLibraryMembers(): $CancellablePromise<apitypes$0.LibraryMemberStatus[]> {
    return $Call.ByID(3506183317).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RemoveLibraryMember(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(1488753536, deviceID);
}

export function RemoveScanRoots(roots: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(139054719, roots).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RenameLibrary(libraryID: string, name: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(439055808, libraryID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ScanRoots(): $CancellablePromise<string[]> {
    return $Call.ByID(4034686803).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SelectLibrary(libraryID: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(2606217906, libraryID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetScanRoots(roots: string[]): $CancellablePromise<void> {
    return $Call.ByID(2099880265, roots);
}

export function StartRescanNow(): $CancellablePromise<desktopcore$0.JobSnapshot> {
    return $Call.ByID(3257783323).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StartRescanRoot(root: string): $CancellablePromise<desktopcore$0.JobSnapshot> {
    return $Call.ByID(2433872449, root).then(($result: any) => {
        return $$createType6($result);
    });
}

export function UpdateLibraryMemberRole(deviceID: string, role: string): $CancellablePromise<void> {
    return $Call.ByID(820385675, deviceID, role);
}

// Private type creation functions
const $$createType0 = apitypes$0.LibrarySummary.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = apitypes$0.LibraryMemberStatus.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = apitypes$0.ScanStats.createFrom;
const $$createType6 = desktopcore$0.JobSnapshot.createFrom;
