// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function GetNotificationPreferences(): $CancellablePromise<apitypes$0.NotificationPreferences> {
    return $Call.ByID(1687951173).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListNotifications(): $CancellablePromise<apitypes$0.NotificationSnapshot[]> {
    return $Call.ByID(1288236570).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetNotificationVerbosity(level: apitypes$0.NotificationVerbosity): $CancellablePromise<apitypes$0.NotificationPreferences> {
    return $Call.ByID(3762528566, level).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SubscribeNotificationEvents(): $CancellablePromise<string> {
    return $Call.ByID(2092711548);
}

// Private type creation functions
const $$createType0 = apitypes$0.NotificationPreferences.createFrom;
const $$createType1 = apitypes$0.NotificationSnapshot.createFrom;
const $$createType2 = $Create.Array($$createType1);
