// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";

export function ExportTraceSession(carrier: apitypes$0.TraceCarrier, sessionID: string, options: apitypes$0.TraceExportOptions): $CancellablePromise<apitypes$0.TraceExportResult> {
    return $Call.ByID(2646479436, carrier, sessionID, options).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetRecentRecords(carrier: apitypes$0.TraceCarrier, filter: apitypes$0.RecentTraceFilter): $CancellablePromise<apitypes$0.TraceRecord[]> {
    return $Call.ByID(1427990958, carrier, filter).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetStatus(carrier: apitypes$0.TraceCarrier): $CancellablePromise<apitypes$0.ObservabilityStatus> {
    return $Call.ByID(4116561865, carrier).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListTraceSessions(carrier: apitypes$0.TraceCarrier, query: apitypes$0.TraceSessionQuery): $CancellablePromise<apitypes$0.TraceSessionSummary[]> {
    return $Call.ByID(3199559895, carrier, query).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RecordFrontendEvents(carrier: apitypes$0.TraceCarrier, batch: apitypes$0.FrontendTraceBatch): $CancellablePromise<void> {
    return $Call.ByID(3917880417, carrier, batch);
}

export function SetLogLevel(carrier: apitypes$0.TraceCarrier, level: string): $CancellablePromise<apitypes$0.ObservabilityStatus> {
    return $Call.ByID(483230363, carrier, level).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartTraceSession(carrier: apitypes$0.TraceCarrier, config: apitypes$0.TraceSessionConfig): $CancellablePromise<apitypes$0.TraceSessionStatus> {
    return $Call.ByID(2551890480, carrier, config).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StopTraceSession(carrier: apitypes$0.TraceCarrier, sessionID: string): $CancellablePromise<apitypes$0.TraceSessionStatus> {
    return $Call.ByID(159014874, carrier, sessionID).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = apitypes$0.TraceExportResult.createFrom;
const $$createType1 = apitypes$0.TraceRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = apitypes$0.ObservabilityStatus.createFrom;
const $$createType4 = apitypes$0.TraceSessionSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = apitypes$0.TraceSessionStatus.createFrom;
