// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "./api/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopcore$0 from "./internal/desktopcore/models.js";

export function GetPinState(req: apitypes$0.PinStateRequest): $CancellablePromise<apitypes$0.PinState> {
    return $Call.ByID(2709485625, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListPinStates(req: apitypes$0.PinStateListRequest): $CancellablePromise<apitypes$0.PinState[]> {
    return $Call.ByID(2586546692, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartPin(req: apitypes$0.PinIntentRequest): $CancellablePromise<desktopcore$0.JobSnapshot> {
    return $Call.ByID(3337195608, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SubscribePinEvents(): $CancellablePromise<string> {
    return $Call.ByID(1018360061);
}

export function Unpin(req: apitypes$0.PinIntentRequest): $CancellablePromise<void> {
    return $Call.ByID(2485350891, req);
}

// Private type creation functions
const $$createType0 = apitypes$0.PinState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = desktopcore$0.JobSnapshot.createFrom;
