// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playback$0 from "./internal/playback/models.js";

export function AppendToQueue(items: playback$0.SessionItem[]): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3298980760, items).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ClearQueue(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3770044668).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetPlaybackSnapshot(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2883480393).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MoveQueueItem(fromIndex: number, toIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2310336635, fromIndex, toIndex).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MoveQueuedEntry(entryID: string, toIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2607667796, entryID, toIndex).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Next(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1638300629).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Pause(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2523925334).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Play(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3337582598).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayAlbum(albumID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2513738197, albumID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayAlbumTrack(albumID: string, recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3154194316, albumID, recordingID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayLiked(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3511599499).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayLikedTrack(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(832559402, recordingID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayPlaylist(playlistID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(4154106592, playlistID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayPlaylistTrack(playlistID: string, itemID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2792974311, playlistID, itemID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function PlayRecording(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2902449013, recordingID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Previous(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(466195825).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QueueAlbum(albumID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3156120874, albumID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QueueItems(items: playback$0.SessionItem[], mode: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2333187429, items, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QueuePlaylist(playlistID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2887176341, playlistID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function QueueRecording(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(48181950, recordingID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveQueueItem(index: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1105181348, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RemoveQueuedEntry(entryID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(622032947, entryID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReplaceQueue(items: playback$0.SessionItem[], startIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3788593979, items, startIndex).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SeekTo(positionMS: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1002348829, positionMS).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectEntry(entryID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3698480776, entryID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectQueueIndex(index: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(325081569, index).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetPlaybackContext(input: playback$0.PlaybackContextInput): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2760603892, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetRepeatMode(mode: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2047165460, mode).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetShuffle(enabled: boolean): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(794069357, enabled).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetVolume(volume: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1816618662, volume).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SubscribePlaybackEvents(): $CancellablePromise<string> {
    return $Call.ByID(4115999572);
}

export function TogglePlayback(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(934724953).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = playback$0.SessionSnapshot.createFrom;
