// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as apitypes$0 from "../core/api/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as playback$0 from "./internal/playback/models.js";

export function ActiveLibrary(): $CancellablePromise<[apitypes$0.LibrarySummary, boolean]> {
    return $Call.ByID(1925253473).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

export function AddPlaylistItem(req: apitypes$0.PlaylistAddItemRequest): $CancellablePromise<apitypes$0.PlaylistItemRecord> {
    return $Call.ByID(3204693674, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AppendToQueue(items: playback$0.SessionItem[]): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3298980760, items).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CleanupCache(req: apitypes$0.CacheCleanupRequest): $CancellablePromise<apitypes$0.CacheCleanupResult> {
    return $Call.ByID(2229260778, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ClearQueue(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3770044668).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateLibrary(name: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(4261975843, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreatePlaylist(name: string, kind: string): $CancellablePromise<apitypes$0.PlaylistRecord> {
    return $Call.ByID(1347071430, name, kind).then(($result: any) => {
        return $$createType4($result);
    });
}

export function DeleteLibrary(libraryID: string): $CancellablePromise<void> {
    return $Call.ByID(2440946874, libraryID);
}

export function DeletePlaylist(playlistID: string): $CancellablePromise<void> {
    return $Call.ByID(4265106209, playlistID);
}

export function GetAlbum(albumID: string): $CancellablePromise<apitypes$0.AlbumListItem> {
    return $Call.ByID(3733101191, albumID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetArtist(artistID: string): $CancellablePromise<apitypes$0.ArtistListItem> {
    return $Call.ByID(3429865259, artistID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetCacheOverview(): $CancellablePromise<apitypes$0.CacheOverview> {
    return $Call.ByID(2171875809).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetPlaybackPreparation(recordingID: string, preferredProfile: string): $CancellablePromise<apitypes$0.PlaybackPreparationStatus> {
    return $Call.ByID(69585430, recordingID, preferredProfile).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetPlaybackSnapshot(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2883480393).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPlaylistSummary(playlistID: string): $CancellablePromise<apitypes$0.PlaylistListItem> {
    return $Call.ByID(46572162, playlistID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function GetRecording(recordingID: string): $CancellablePromise<apitypes$0.RecordingListItem> {
    return $Call.ByID(3081840451, recordingID).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetRecordingAvailability(recordingID: string, preferredProfile: string): $CancellablePromise<apitypes$0.RecordingPlaybackAvailability> {
    return $Call.ByID(1097737044, recordingID, preferredProfile).then(($result: any) => {
        return $$createType11($result);
    });
}

export function InspectPlaybackRecording(recordingID: string, preferredProfile: string): $CancellablePromise<apitypes$0.PlaybackPreparationStatus> {
    return $Call.ByID(3914385752, recordingID, preferredProfile).then(($result: any) => {
        return $$createType8($result);
    });
}

export function IsRecordingLiked(recordingID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3192503848, recordingID);
}

export function LeaveLibrary(libraryID: string): $CancellablePromise<void> {
    return $Call.ByID(3952630774, libraryID);
}

export function LikeRecording(recordingID: string): $CancellablePromise<void> {
    return $Call.ByID(788122698, recordingID);
}

export function ListAlbumTracks(req: apitypes$0.AlbumTrackListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumTrackItem>> {
    return $Call.ByID(1946162099, req).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ListAlbumVariants(req: apitypes$0.AlbumVariantListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumVariantItem>> {
    return $Call.ByID(4208882965, req).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListAlbums(req: apitypes$0.AlbumListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumListItem>> {
    return $Call.ByID(3591213824, req).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListArtistAlbums(req: apitypes$0.ArtistAlbumListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.AlbumListItem>> {
    return $Call.ByID(1792926887, req).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListArtists(req: apitypes$0.ArtistListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.ArtistListItem>> {
    return $Call.ByID(2482442412, req).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ListCacheEntries(req: apitypes$0.CacheEntryListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.CacheEntryItem>> {
    return $Call.ByID(3080494030, req).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ListLibraries(): $CancellablePromise<apitypes$0.LibrarySummary[]> {
    return $Call.ByID(2538907463).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ListLibraryMembers(): $CancellablePromise<apitypes$0.LibraryMemberStatus[]> {
    return $Call.ByID(1491866554).then(($result: any) => {
        return $$createType22($result);
    });
}

export function ListLikedRecordings(req: apitypes$0.LikedRecordingListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.LikedRecordingItem>> {
    return $Call.ByID(627425737, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function ListPlaylistTracks(req: apitypes$0.PlaylistTrackListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.PlaylistTrackItem>> {
    return $Call.ByID(531454606, req).then(($result: any) => {
        return $$createType26($result);
    });
}

export function ListPlaylists(req: apitypes$0.PlaylistListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.PlaylistListItem>> {
    return $Call.ByID(1367076171, req).then(($result: any) => {
        return $$createType27($result);
    });
}

export function ListRecordingAvailability(recordingID: string, preferredProfile: string): $CancellablePromise<apitypes$0.RecordingAvailabilityItem[]> {
    return $Call.ByID(3562379088, recordingID, preferredProfile).then(($result: any) => {
        return $$createType29($result);
    });
}

export function ListRecordingVariants(req: apitypes$0.RecordingVariantListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.RecordingVariantItem>> {
    return $Call.ByID(1269045609, req).then(($result: any) => {
        return $$createType31($result);
    });
}

export function ListRecordings(req: apitypes$0.RecordingListRequest): $CancellablePromise<apitypes$0.Page<apitypes$0.RecordingListItem>> {
    return $Call.ByID(792755444, req).then(($result: any) => {
        return $$createType32($result);
    });
}

export function MovePlaylistItem(req: apitypes$0.PlaylistMoveItemRequest): $CancellablePromise<apitypes$0.PlaylistItemRecord> {
    return $Call.ByID(4147935104, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function MoveQueueItem(fromIndex: number, toIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2310336635, fromIndex, toIndex).then(($result: any) => {
        return $$createType2($result);
    });
}

export function MoveQueuedEntry(entryID: string, toIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2607667796, entryID, toIndex).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Next(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1638300629).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Pause(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2523925334).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Play(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3337582598).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayAlbum(albumID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2513738197, albumID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayAlbumTrack(albumID: string, recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3154194316, albumID, recordingID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayLiked(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3511599499).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayLikedTrack(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(832559402, recordingID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayPlaylist(playlistID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(4154106592, playlistID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayPlaylistTrack(playlistID: string, itemID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2792974311, playlistID, itemID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PlayRecording(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2902449013, recordingID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function PreparePlaybackRecording(recordingID: string, preferredProfile: string, purpose: apitypes$0.PlaybackPreparationPurpose): $CancellablePromise<apitypes$0.PlaybackPreparationStatus> {
    return $Call.ByID(291423697, recordingID, preferredProfile, purpose).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Previous(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(466195825).then(($result: any) => {
        return $$createType2($result);
    });
}

export function QueueAlbum(albumID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3156120874, albumID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function QueueItems(items: playback$0.SessionItem[], mode: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2333187429, items, mode).then(($result: any) => {
        return $$createType2($result);
    });
}

export function QueuePlaylist(playlistID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2887176341, playlistID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function QueueRecording(recordingID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(48181950, recordingID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveLibraryMember(deviceID: string): $CancellablePromise<void> {
    return $Call.ByID(3304724277, deviceID);
}

export function RemovePlaylistItem(playlistID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(914233465, playlistID, itemID);
}

export function RemoveQueueItem(index: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1105181348, index).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RemoveQueuedEntry(entryID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(622032947, entryID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function RenameLibrary(libraryID: string, name: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(3344110257, libraryID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RenamePlaylist(playlistID: string, name: string): $CancellablePromise<apitypes$0.PlaylistRecord> {
    return $Call.ByID(1120003992, playlistID, name).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ReplaceQueue(items: playback$0.SessionItem[], startIndex: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3788593979, items, startIndex).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ResolveBlobURL(blobID: string): $CancellablePromise<string> {
    return $Call.ByID(3481719932, blobID);
}

export function ResolvePlaybackRecording(recordingID: string, preferredProfile: string): $CancellablePromise<apitypes$0.PlaybackResolveResult> {
    return $Call.ByID(1410932048, recordingID, preferredProfile).then(($result: any) => {
        return $$createType33($result);
    });
}

export function ResolveRecordingArtworkURL(recordingID: string, variant: string): $CancellablePromise<string> {
    return $Call.ByID(1531284046, recordingID, variant);
}

export function ResolveThumbnailURL(artwork: apitypes$0.ArtworkRef): $CancellablePromise<string> {
    return $Call.ByID(2195486573, artwork);
}

export function SeekTo(positionMS: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1002348829, positionMS).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SelectEntry(entryID: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(3698480776, entryID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SelectLibrary(libraryID: string): $CancellablePromise<apitypes$0.LibrarySummary> {
    return $Call.ByID(4060872783, libraryID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelectQueueIndex(index: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(325081569, index).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPlaybackContext(input: playback$0.PlaybackContextInput): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2760603892, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPreferredAlbumVariant(albumID: string, variantAlbumID: string): $CancellablePromise<void> {
    return $Call.ByID(1629338945, albumID, variantAlbumID);
}

export function SetPreferredRecordingVariant(recordingID: string, variantRecordingID: string): $CancellablePromise<void> {
    return $Call.ByID(2747824353, recordingID, variantRecordingID);
}

export function SetRepeatMode(mode: string): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(2047165460, mode).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetShuffle(enabled: boolean): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(794069357, enabled).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetVolume(volume: number): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(1816618662, volume).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SubscribePlaybackEvents(): $CancellablePromise<string> {
    return $Call.ByID(4115999572);
}

export function TogglePlayback(): $CancellablePromise<playback$0.SessionSnapshot> {
    return $Call.ByID(934724953).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UnlikeRecording(recordingID: string): $CancellablePromise<void> {
    return $Call.ByID(467937703, recordingID);
}

export function UpdateLibraryMemberRole(deviceID: string, role: string): $CancellablePromise<void> {
    return $Call.ByID(557539354, deviceID, role);
}

// Private type creation functions
const $$createType0 = apitypes$0.LibrarySummary.createFrom;
const $$createType1 = apitypes$0.PlaylistItemRecord.createFrom;
const $$createType2 = playback$0.SessionSnapshot.createFrom;
const $$createType3 = apitypes$0.CacheCleanupResult.createFrom;
const $$createType4 = apitypes$0.PlaylistRecord.createFrom;
const $$createType5 = apitypes$0.AlbumListItem.createFrom;
const $$createType6 = apitypes$0.ArtistListItem.createFrom;
const $$createType7 = apitypes$0.CacheOverview.createFrom;
const $$createType8 = apitypes$0.PlaybackPreparationStatus.createFrom;
const $$createType9 = apitypes$0.PlaylistListItem.createFrom;
const $$createType10 = apitypes$0.RecordingListItem.createFrom;
const $$createType11 = apitypes$0.RecordingPlaybackAvailability.createFrom;
const $$createType12 = apitypes$0.AlbumTrackItem.createFrom;
const $$createType13 = apitypes$0.Page.createFrom($$createType12);
const $$createType14 = apitypes$0.AlbumVariantItem.createFrom;
const $$createType15 = apitypes$0.Page.createFrom($$createType14);
const $$createType16 = apitypes$0.Page.createFrom($$createType5);
const $$createType17 = apitypes$0.Page.createFrom($$createType6);
const $$createType18 = apitypes$0.CacheEntryItem.createFrom;
const $$createType19 = apitypes$0.Page.createFrom($$createType18);
const $$createType20 = $Create.Array($$createType0);
const $$createType21 = apitypes$0.LibraryMemberStatus.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = apitypes$0.LikedRecordingItem.createFrom;
const $$createType24 = apitypes$0.Page.createFrom($$createType23);
const $$createType25 = apitypes$0.PlaylistTrackItem.createFrom;
const $$createType26 = apitypes$0.Page.createFrom($$createType25);
const $$createType27 = apitypes$0.Page.createFrom($$createType9);
const $$createType28 = apitypes$0.RecordingAvailabilityItem.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = apitypes$0.RecordingVariantItem.createFrom;
const $$createType31 = apitypes$0.Page.createFrom($$createType30);
const $$createType32 = apitypes$0.Page.createFrom($$createType10);
const $$createType33 = apitypes$0.PlaybackResolveResult.createFrom;
