// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as palette$0 from "./internal/palette/models.js";

export function GenerateRecordingTheme(recordingID: string): $CancellablePromise<palette$0.ThemePalette> {
    return $Call.ByID(2624863662, recordingID).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = palette$0.ThemePalette.createFrom;
